# -*- coding: utf-8 -*-
"""68050123_Lab01

Automatically generated by Colab.

"""

from google.colab import files
uploaded = files.upload()

import pandas as pd
df = pd.read_csv( 'Churn_Modelling.csv' )

import matplotlib.pyplot as plt
import seaborn as sns
sns.set_style('darkgrid')
colors = ['#00A5E0', '#DD403A']

fig = plt.figure(figsize = (12, 8))
sns.boxplot(y='Balance',x = 'Geography', hue = 'Exited', data = df)